---
collections:
  - name: https://opendev.org/openstack/ansible-config_template
    version: master
    type: git
  - name: https://opendev.org/openstack/openstack-ansible-plugins
    version: master
    type: git
  - name: https://github.com/ansible-collections/ansible.utils
    version: v6.0.0
    type: git
  - name: https://github.com/ansible-collections/community.crypto
    type: git
    version: 2.26.2
roles:
  - name: pki
    src: https://opendev.org/openstack/ansible-role-pki
    scm: git
    version: master

  - name: systemd_service
    src: https://opendev.org/openstack/ansible-role-systemd_service
    scm: git
    version: master
